### ISSUE TITLE
please verify that dependencies are installed and that the task exists.

### ISSUE THREAD

**Issue by ZhengyeHan** [nicklashansen/tdmpc2#31]
My computer system is macOS:
I cloned your code to my local machine using git clone and installed the required dependencies. Then, I set hydra/launcher in config.yaml to basic. I noticed that there are predefined environments in envs/tasks, so I set the task in config.yaml to one of the existing filenames in envs/tasks, for example, hopper. However, when I run the script, I get the following error message:

```
Error executing job with overrides: []
Traceback (most recent call last):
File "/Users/zhengyehan/Desktop/TDMPC2/tdmpc2/tdmpc2/train.py", line 53, in train
env=make_env(cfg),
File "/Users/zhengyehan/Desktop/TDMPC2/tdmpc2/tdmpc2/envs/.init..py", line 71, in make_env
raise ValueError(f'Failed to make environment "{cfg.task}": please verify that dependencies are installed and that the task exists.')
ValueError: Failed to make environment "hopper": please verify that dependencies are installed and that the task exists.
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Could you please help me solve this issue? Thank you!

**Comment by nicklashansen** [comment]
I have not tested the codebase on macOS so I'm not sure what the potential issues might be, but I second what @mpont said re: using a linux environment. As an aside, please double-check that the task does indeed exist, e.g., `cfg.task=hopper-hop` is a valid task but `cfg.task=hopper` is not.

**Comment by anh-nn01** [comment]
I also encountered this issue for Meta-World envs, although it ran without any problem for DMControl tasks.

In my case, the issue was cause by the imports in `envs/__init__.py`
```
try:
	from envs.metaworld import make_env as make_metaworld_env
except:
	make_metaworld_env = missing_dependencies
```

The error causing the issue was `[Errno 2] No such file or directory: 'patchelf'`, which can be solved by `sudo apt-get install patchelf`. If you are using server without sudo permission to install patchelf, you can create a conda env instead.

Since the code uses exception handling, it does not pinpoint the exact problem, so I had to manually trace it down. You can start by tracing the error from `envs/__init__.py`.

**Comment by nicklashansen** [comment]
Thank you @anh-nn01 for sharing your solution! I will close this issue.
